In [1]:
import connectNvironment as connect
import random
import numpy as np

Make environment

In [2]:
env = connect.ConnectN()

Show and get current state

In [6]:
print(env)

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [7]:
env.board

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

Performing actions

In [8]:
env.step(0)

In [9]:
env.board

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0]])

In [10]:
env.step(6)

In [11]:
env.board

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 2]])

Random action

In [44]:
action = env.get_legal_random_action()

In [45]:
env.step(action)

In [46]:
env.board

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 2]])

The current player 

In [49]:
env.current_player

2

Check if the game is over

In [12]:
env.is_game_over

False

## Exercise 1)
Create a network you think will do well on this task.

### Answer)

In [1]:
from tensorflow.keras.layers import Dense, Conv2D, Flatten
from tensorflow.keras.models import Sequential

In [2]:
env.board.shape

NameError: name 'env' is not defined

In [5]:
input_shape = (6, 7, 3) # 3 values: 1) the actual piece, 2) the current player, 3) The player who is playing
number_of_actions = 7

model = Sequential([
    Conv2D(16, (4,4), activation="relu", input_shape=input_shape),
    Flatten(),
    Dense(128, activation="relu"),
    Dense(32, activation="relu"),
    Dense(number_of_actions)
])

2022-04-18 14:19:05.173149: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-04-18 14:19:05.201451: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-04-18 14:19:05.201697: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-04-18 14:19:05.202339: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags

## Exercise 2)
Preprocess the state of the game for your model. Try if it works.

In [6]:
env.board.shape

(6, 7)

In [7]:
env.current_player

1

In [8]:
agent_number = 1

board_data = env.board.reshape(1,6,7,1)
current_player_data = env.current_player * np.ones((1,6,7,1))
agent_player_data = agent_number *np.ones((1,6,7,1))

input_data = np.concatenate([board_data, current_player_data, agent_player_data],axis=3)

In [9]:
input_data.shape

(1, 6, 7, 3)

In [10]:
input_data

array([[[[0., 1., 1.],
         [0., 1., 1.],
         [0., 1., 1.],
         [0., 1., 1.],
         [0., 1., 1.],
         [0., 1., 1.],
         [0., 1., 1.]],

        [[0., 1., 1.],
         [0., 1., 1.],
         [0., 1., 1.],
         [0., 1., 1.],
         [0., 1., 1.],
         [0., 1., 1.],
         [0., 1., 1.]],

        [[0., 1., 1.],
         [0., 1., 1.],
         [0., 1., 1.],
         [0., 1., 1.],
         [0., 1., 1.],
         [0., 1., 1.],
         [0., 1., 1.]],

        [[0., 1., 1.],
         [0., 1., 1.],
         [0., 1., 1.],
         [0., 1., 1.],
         [0., 1., 1.],
         [0., 1., 1.],
         [0., 1., 1.]],

        [[0., 1., 1.],
         [0., 1., 1.],
         [0., 1., 1.],
         [0., 1., 1.],
         [0., 1., 1.],
         [0., 1., 1.],
         [0., 1., 1.]],

        [[0., 1., 1.],
         [0., 1., 1.],
         [0., 1., 1.],
         [0., 1., 1.],
         [0., 1., 1.],
         [0., 1., 1.],
         [0., 1., 1.]]]])

In [11]:
model(input_data)

2022-04-18 14:19:07.764679: I tensorflow/stream_executor/cuda/cuda_dnn.cc:368] Loaded cuDNN version 8302


<tf.Tensor: shape=(1, 7), dtype=float32, numpy=
array([[ 0.09756156, -0.21895024, -0.26296663, -0.05115595, -0.13444373,
         0.04534294, -0.33866668]], dtype=float32)>

## Exercise 3)
Assign values to:

In [12]:
learning_rate = 10e-4 # alpha

## Exercise 4) 
Compile the model

In [13]:
from tensorflow.keras.optimizers import Adam
model.compile(optimizer=Adam(learning_rate),loss="mse")

## Exercise 5)
Assign values to:

In [14]:
epsilon_max = 1
epsilon_min = 0.1
epsilon_decay = 0.995
epsilon = epsilon_max

gamma = 0.99

number_of_games = 400
max_number_of_steps = 1000 # It's limited by the size of the board

reward_win = 1
reward_lose = -1 
reward_tie = 0

## Exercise 6)
Train one agent using vanila Deep Q Learning. Let the agent play against a random generator. 

Note: Don't expect a good result

In [46]:
agent_number = 1
winners = []

for game_index in range(number_of_games):
    
    env = connect.ConnectN()
    
    # Handle the epilon values
    epsilon *= epsilon_decay
    if epsilon < epsilon_min:
        epsilon = epsilon_min
        
    step_index = 0
    while env.is_game_over == False:
        step_index+=1
        
        # Your agents turn
        if agent_number != env.current_player:
            raise RuntimeError("Wrong player")
    
        # Get current state
        board_data = env.board.reshape(1,6,7,1)
        current_player_data = env.current_player * np.ones((1,6,7,1))
        agent_player_data = agent_number * np.ones((1,6,7,1))
        current_obsv = np.concatenate([board_data, current_player_data, agent_player_data],axis=3)
    
        # Predict Q values of current state
        current_q_values = model.predict(current_obsv)[0]
        
        # Determine action
        if random.random() < epsilon:
            # Perform random action
            action = env.get_legal_random_action()
        else:
            legal_actions = env.get_legal_actions()
            action = legal_actions[np.argmax(current_q_values[legal_actions])]
            
        # Perform action
        env.step(action)
            
        # Your agents oppenent
        if env.is_game_over == False:
            action = env.get_legal_random_action()
            env.step(action)
        
        # Get new state (this is not used when the game is over)
        board_data = env.board.reshape(1,6,7,1)
        current_player_data = env.current_player * np.ones((1,6,7,1))
        agent_player_data = agent_number * np.ones((1,6,7,1))
        next_obsv = np.concatenate([board_data, current_player_data, agent_player_data],axis=3)
        
        # Predict Q values of new state (this is not used when the game is over)
        next_q_values = model.predict(next_obsv)[0]
        
        # Handle rewards
        if env.is_game_over == False:
            reward = 0
        else:
            if env.winner == agent_number:
                reward = reward_win
            elif env.winner == 0:
                reward = reward_tie
            else:
                reward = reward_lose
                
        # Calculate new Q values    
        if env.is_game_over == True:
            current_q_values[action] = reward
        else:
            q_max_next = np.max(next_q_values)
            current_q_values[action] = reward + gamma*q_max_next
            
        # Train the model
        model.train_on_batch(current_obsv, current_q_values.reshape(1,-1))
        
    winners.append(env.winner)
    
    if len(winners) % 10 == 0:
        agent_wins = np.sum(np.array(winners[-10:]) == agent_number)
        print(game_index, agent_wins, epsilon)
        

9 6 0.8183201210226743
19 7 0.778312557068642


KeyboardInterrupt: 

## Exercise 7) 
Create code to play against the AI

In [17]:
env = connect.ConnectN()

In [30]:
print(env)

# Get observation
board_data = env.board.reshape(1,6,7,1)
current_player_data = env.current_player * np.ones((1,6,7,1))
agent_player_data = agent_number * np.ones((1,6,7,1))
current_obsv = np.concatenate([board_data, current_player_data, agent_player_data],axis=3)

# Predict Q values of current state
current_q_values = model.predict(current_obsv)[0]

# Determine action
legal_actions = env.get_legal_actions()
action = legal_actions[np.argmax(current_q_values[legal_actions])]

# Perform action
env.step(action)

print(env)

[[0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 1 2 0 0 0 0]
 [0 1 2 2 2 2 1]]


RuntimeError: Game is already over

In [29]:
# My action
env.step(5)

## Exercise 8) 
Create an evaluation function to monitor how good the AI is doing against a random generator.

In [31]:
def evaluate(model, agent_number, number_of_games=10):
    winners = []
    for game_index in range(number_of_games):
    
        env = connect.ConnectN()

        while env.is_game_over == False:

            # Handle the opponent
            if agent_number != env.current_player:
                action = env.get_legal_random_action()
                env.step(action)
                continue

            # Get current state
            board_data = env.board.reshape(1,6,7,1)
            current_player_data = env.current_player * np.ones((1,6,7,1))
            agent_player_data = agent_number * np.ones((1,6,7,1))
            current_obsv = np.concatenate([board_data, current_player_data, agent_player_data],axis=3)

            # Predict Q values of current state
            current_q_values = model.predict(current_obsv)[0]

            # Determine action
            legal_actions = env.get_legal_actions()
            action = legal_actions[np.argmax(current_q_values[legal_actions])]

            # Perform action
            env.step(action)
            
        winners.append(env.winner)
    return np.mean(np.array(winners) == agent_number)

In [32]:
evaluate(model, 1)

0.8

## Exercise 9)
Retrain the AI in which it plays against itself. Evaluate your model every 10 games

Note: Don't expect a good result

In [139]:
input_shape = (6, 7, 3) # 3 values: 1) the actual piece, 2) the current player, 3) The player who is playing
number_of_actions = 7

model = Sequential([
    Conv2D(16, (4,4), activation="relu", input_shape=input_shape),
    Flatten(),
    Dense(128, activation="relu"),
    Dense(32, activation="relu"),
    Dense(number_of_actions)
])

In [140]:
gamma = 0.99
learning_rate = 10e-4 # alpha

In [141]:
from tensorflow.keras.optimizers import Adam
model.compile(optimizer=Adam(learning_rate),loss="mse")

In [142]:
epsilon_max = 1
epsilon_min = 0.1
epsilon_decay = 0.995
epsilon = epsilon_max

number_of_games = 400
max_number_of_steps = 1000 # It's limited by the size of the board

reward_win = 1
reward_lose = -1 
reward_tie = 0

In [194]:
win_rates = []

agents = [1,2]

for game_index in range(number_of_games):
    
    # Switch agent number every game (just to keep the code simpel)
    agent_number = agents[game_index % 2]
    opponent_agent_number = agents[(game_index + 1) % 2]
    
    # Create a new environement
    env = connect.ConnectN()
    
    # Handle the epilon values
    epsilon *= epsilon_decay
    if epsilon < epsilon_min:
        epsilon = epsilon_min
        
    for step_index in range(100):
        
        # Handle the opponent
        if agent_number != env.current_player and env.is_game_over == False:
        
            # Perform action of opponent
            board_data = env.board.reshape(1,6,7,1)
            current_player_data = env.current_player * np.ones((1,6,7,1))
            agent_player_data = env.current_player * np.ones((1,6,7,1))
            opponent_obsv = np.concatenate([board_data, current_player_data, agent_player_data],axis=3)
            
            # Predict Q values of current state
            opponent_q_values = model.predict(opponent_obsv)[0]
            
            # Get action
            legal_actions = env.get_legal_actions()
            action = legal_actions[np.argmax(opponent_q_values[legal_actions])]
            
            # Perform action
            env.step(action)
            
            
        # Get current state
        board_data = env.board.reshape(1,6,7,1)
        current_player_data = env.current_player * np.ones((1,6,7,1))
        agent_player_data = agent_number * np.ones((1,6,7,1))
        current_obsv = np.concatenate([board_data, current_player_data, agent_player_data],axis=3)
    
        # Predict Q values of current state
        current_q_values = model.predict(current_obsv)[0]
        
        # Now we will start with training first
        if step_index > 1:
            
            # Handle rewards
            if env.is_game_over == False:
                reward = 0
            else:
                if env.winner == agent_number:
                    reward = reward_win
                elif env.winner == -1 | env.winner == 0:
                    reward = reward_tie
                else:
                    reward = reward_lose

            # Calculate new Q values    
            if env.is_game_over == True:
                previous_q_values[previous_action] = reward
            else:
                q_max_next = np.max(current_q_values)
                previous_q_values[previous_action] = reward + gamma*q_max_next

            # Train the model
            model.train_on_batch(previous_obsv, previous_q_values.reshape(1,-1))
        
        # Now we have to break the loop because we want to train a batch after we have won
        if env.is_game_over:
            break
        
        # Determine action
        if random.random() < epsilon:
            # Perform random action
            action = env.get_legal_random_action()
        else:
            legal_actions = env.get_legal_actions()
            action = legal_actions[np.argmax(current_q_values[legal_actions])]
            
        # Perform action
        env.step(action)
        
        # Store the current state and q values
        previous_obsv = current_obsv
        previous_q_values = current_q_values
        previous_action = action
        
    if game_index % 10 == 0:
        win_rate = evaluate(model, 1)
        print(game_index, win_rate, epsilon)
        win_rates.append(win_rate)
        

0 0.9 0.6027415843082742


KeyboardInterrupt: 

## Exercise 10)
Play against the new AI

In [144]:
env = connect.ConnectN()

In [149]:
print(env)

# Get observation
board_data = env.board.reshape(1,6,7,1)
current_player_data = env.current_player * np.ones((1,6,7,1))
agent_player_data = agent_number * np.ones((1,6,7,1))
current_obsv = np.concatenate([board_data, current_player_data, agent_player_data],axis=3)

# Predict Q values of current state
current_q_values = model.predict(current_obsv)[0]

# Determine action
legal_actions = env.get_legal_actions()
action = legal_actions[np.argmax(current_q_values[legal_actions])]

# Perform action
env.step(action)

print(env)

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 1 2 0 0 0 0]]
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 1 2 0 0 0 0]]


In [148]:
env.step(1)

## Exercise 11)
Create a memory class or set of functions which can do the following:
- Can hold an X amount memories
- You can add state, next_state, action, reward and if the game is over to the memory
- You can take a batch of X 
    - Bonus 1: this memory will not return empty memory states
    - Bonus 2: without the change of picking one sample twice
- FiFo: It will remove the oldest states when there are too many states in memory

In [362]:
class Memory():
    
    def __init__(self, er_size=1000, batch_size=256, state_shape=(6, 7, 3)):
        
        self.er_size = er_size
        self.batch_size = batch_size
        
        self.states = np.zeros([er_size, *state_shape])
        self.next_states = np.zeros([er_size, *state_shape])
        self.actions = np.zeros(er_size, dtype=int)
        self.rewards = np.zeros(er_size)
        self.alives = np.zeros(er_size)
        
        self.index = 0
        self.max_index = 0
        
    def add_event(self, state, next_state, action, reward, is_alive):
        
        # Add new situation
        self.states[self.index] = state
        self.next_states[self.index] = next_state
        self.actions[self.index] = action
        self.rewards[self.index] = reward
        self.alives[self.index] = is_alive
        
        # Update indices
        self.index += 1
        if self.index > self.er_size - 1:
            self.index = 0
        self.max_index = np.max([self.index, self.max_index])
        
    def take_batch(self, batch_size=None):
        # Just to make this method a bit more flexible
        if batch_size == None:
            batch_size = self.batch_size
            
        # Inidices of batch
        num_of_samples = np.min([self.max_index, self.er_size])
        batch_size = np.min([num_of_samples, batch_size])
        indices = np.random.choice(range(num_of_samples), batch_size, replace=False)
        
        return [
            self.states[indices],
            self.next_states[indices],
            self.actions[indices],
            self.rewards[indices],
            self.alives[indices]
        ]

In [363]:
memory = Memory()

In [364]:
memory.add_event(previous_obsv[0], current_obsv[0], action, reward, not env.is_game_over)
memory.add_event(previous_obsv[0], current_obsv[0], action, reward, not env.is_game_over)

In [365]:
memory.take_batch()[0].shape

(2, 6, 7, 3)

## Exercise 12)
Add experience replay to the loop without the training part. Fill a memory of length 10.000 with both agents using a random action policy.

In [315]:
er_size = 10_000
batch_size = 256

In [316]:
memory = Memory(er_size=er_size, batch_size=batch_size)

In [317]:
agents = [1,2]

game_index = 0
while memory.max_index < er_size-1:
    game_index+=1
    
    # Switch agent number every game (just to keep the code simpel)
    agent_number = agents[game_index % 2]
    opponent_agent_number = agents[(game_index + 1) % 2]
    
    # Create a new environement
    env = connect.ConnectN()
    
    # Handle the epilon values
    epsilon *= epsilon_decay
    if epsilon < epsilon_min:
        epsilon = epsilon_min
        
    print(memory.max_index, agent_number)
        
    for step_index in range(100):
        
        # Handle the opponent
        if agent_number != env.current_player and env.is_game_over == False:
            
            action = env.get_legal_random_action()
            env.step(action)
            continue
            
        # Get current state
        board_data = env.board.reshape(1,6,7,1)
        current_player_data = env.current_player * np.ones((1,6,7,1))
        agent_player_data = agent_number * np.ones((1,6,7,1))
        current_obsv = np.concatenate([board_data, current_player_data, agent_player_data],axis=3)
        
        # Now we will start with training first
        if step_index > 1:
            
            # Handle rewards
            if env.is_game_over == False:
                reward = 0
            else:
                if env.winner == agent_number:
                    reward = reward_win
                elif env.winner == -1 | env.winner == 0:
                    reward = reward_tie
                else:
                    reward = reward_lose
                    
            # Add experience to memory
            memory.add_event(previous_obsv[0], current_obsv[0], previous_action, reward, not env.is_game_over)
        
        # Now we have to break the loop because we want to train a batch after we have won
        if env.is_game_over:
            break
        
        # Determine action
        action = env.get_legal_random_action()
            
        # Perform action
        env.step(action)
        
        # Store the current state and q values
        previous_obsv = current_obsv
        previous_action = action

0 2
0 1
17 2
25 1
36 2
53 1
64 2
81 1
103 2
116 1
127 2
139 1
146 2
159 1
164 2
174 1
188 2
199 1
205 2
221 1
236 2
249 1
261 2
278 1
291 2
300 1
313 2
325 1
334 2
345 1
353 2
367 1
374 2
386 1
400 2
405 1
412 2
425 1
434 2
445 1
455 2
474 1
487 2
502 1
517 2
527 1
543 2
556 1
576 2
586 1
593 2
598 1
604 2
618 1
627 2
632 1
642 2
661 1
676 2
691 1
700 2
708 1
719 2
731 1
744 2
748 1
760 2
774 1
783 2
789 1
799 2
804 1
817 2
833 1
850 2
856 1
871 2
883 1
894 2
908 1
924 2
939 1
950 2
963 1
977 2
984 1
996 2
1006 1
1017 2
1025 1
1033 2
1051 1
1064 2
1069 1
1083 2
1094 1
1107 2
1118 1
1126 2
1135 1
1147 2
1159 1
1171 2
1175 1
1180 2
1184 1
1195 2
1201 1
1220 2
1230 1
1241 2
1254 1
1259 2
1281 1
1303 2
1319 1
1334 2
1346 1
1360 2
1374 1
1381 2
1394 1
1409 2
1417 1
1434 2
1448 1
1465 2
1480 1
1488 2
1503 1
1510 2
1524 1
1537 2
1548 1
1565 2
1576 1
1588 2
1605 1
1612 2
1625 1
1642 2
1654 1
1660 2
1671 1
1685 2
1703 1
1708 2
1721 1
1737 2
1753 1
1766 2
1782 1
1799 2
1807 1
1822 2
1837 1
1847 

## Exercise 13)
Train a model which is good at connect 4 using you the obtained experiences

In [318]:
input_shape = (6, 7, 3) # 3 values: 1) the actual piece, 2) the current player, 3) The player who is playing
number_of_actions = 7

model = Sequential([
    Conv2D(16, (4,4), activation="relu", input_shape=input_shape),
    Flatten(),
    Dense(128, activation="relu"),
    Dense(32, activation="relu"),
    Dense(number_of_actions)
])

In [319]:
gamma = 0.99
learning_rate = 10e-4 # alpha

In [320]:
from tensorflow.keras.optimizers import Adam
model.compile(optimizer=Adam(learning_rate),loss="mse")

In [321]:
epsilon_max = 1
epsilon_min = 0.1
epsilon_decay = 0.995
epsilon = epsilon_max

number_of_games = 400
max_number_of_steps = 1000 # It's limited by the size of the board

reward_win = 1
reward_lose = -1 
reward_tie = 0


In [322]:
memory.max_index

9999

In [323]:
is_alives

array([1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
       1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [324]:
rewards

array([ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,
        0.,  0.,  0.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [331]:
losses = []

counter = 0
while True:
    
    batch = memory.take_batch()
    
    batch_size = len(batch[0])
    state = batch[0]
    next_state = batch[1]
    actions = batch[2].astype(int)
    rewards = batch[3]
    is_alives = batch[4]
    
    # Current state Q values
    q_current_values = model.predict(state)
    
    # Next state Q values
    q_next_values = model.predict(next_state)
    q_max_next_values = np.max(q_next_values,axis=1)
    
    # Calculate the new Q values
    new_q_values = rewards + gamma * q_max_next_values * is_alives
    
    # Set the new Q values
    q_current_values[range(batch_size), actions] = new_q_values

    # Train the model
    loss = model.train_on_batch(state, q_current_values)
    
    # Append loss
    losses.append(loss)
    
    # Show result
    if counter % 50 == 0:
        print(counter, loss)
    counter+=1

0 5.041001319885254
50 1377.7802734375
100 12.314291954040527
150 0.5073269009590149
200 2.529031753540039
250 0.2276521772146225
300 0.10832904279232025
350 0.1788529008626938
400 0.14135678112506866
450 0.12172527611255646
500 0.06765390187501907
550 0.18284690380096436
600 0.11343161016702652
650 0.043084219098091125
700 0.06197086721658707
750 0.05934178829193115
800 0.03499094396829605
850 0.04969916120171547
900 0.02069902792572975
950 0.048963092267513275
1000 0.013868752866983414
1050 0.20331579446792603
1100 0.14506807923316956
1150 0.0894361287355423
1200 0.008156972005963326
1250 0.07102528214454651
1300 0.13504254817962646
1350 0.09590959548950195
1400 0.06681095063686371
1450 0.06373511999845505
1500 0.07570470124483109
1550 0.1120438426733017
1600 0.03296547383069992
1650 0.04669124633073807
1700 0.019297922030091286
1750 0.10789817571640015
1800 0.08210226893424988
1850 0.03647007793188095
1900 0.03734070807695389
1950 0.03988011181354523
2000 0.04082217812538147
2050 0.

KeyboardInterrupt: 

## Exerices 14) 
Play against the new AI

In [345]:
env = connect.ConnectN()

In [354]:
print(env)

# Get observation
board_data = env.board.reshape(1,6,7,1)
current_player_data = env.current_player * np.ones((1,6,7,1))
agent_player_data = agent_number * np.ones((1,6,7,1))
current_obsv = np.concatenate([board_data, current_player_data, agent_player_data],axis=3)

# Predict Q values of current state
current_q_values = model.predict(current_obsv)[0]

# Determine action
legal_actions = env.get_legal_actions()
action = legal_actions[np.argmax(current_q_values[legal_actions])]

# Perform action
env.step(action)

print(env)

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1]
 [0 1 2 2 2 2 1]]


RuntimeError: Game is already over

In [353]:
env.step(2)

## Exercise 15)
Complete the Q Learning with experience replay

In [436]:
input_shape = (6, 7, 3) # 3 values: 1) the actual piece, 2) the current player, 3) The player who is playing
number_of_actions = 7

model = Sequential([
    Conv2D(16, (4,4), activation="relu", input_shape=input_shape),
    Flatten(),
    Dense(128, activation="relu"),
    Dense(32, activation="relu"),
    Dense(number_of_actions)
])

In [437]:
gamma = 0.99
learning_rate = 10e-4 # alpha

In [438]:
from tensorflow.keras.optimizers import Adam
model.compile(optimizer=Adam(learning_rate),loss="mse")

In [439]:
epsilon_max = 1
epsilon_min = 0.1
epsilon_decay = 0.999
epsilon = epsilon_max

number_of_games = 100_000
max_number_of_steps = 1000 # It's limited by the size of the board

reward_win = 1
reward_lose = -1 
reward_tie = 0


In [440]:
er_size = 10_000
batch_size = 256

In [441]:
memory = Memory(er_size=er_size, batch_size=batch_size)

In [463]:
np.arange(256)[batch[3] == -1]

array([  9,  31,  53,  67,  74,  83,  86,  87,  95, 103, 107, 110, 114,
       120, 153, 177, 193, 195, 199, 201, 213, 215, 225, 229, 245, 255])

In [464]:
batch[3][9]

-1.0

In [469]:
batch[0][9,:,:,0]

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0., 0., 0.],
       [0., 2., 1., 1., 1., 0., 0.]])

In [488]:
model.predict(batch[0][9:10])

array([[0.40236452, 0.5046275 , 0.47732276, 0.41945544, 0.43618745,
        0.3563146 , 0.29618275]], dtype=float32)

In [489]:
batch[2][9:10]

array([6])

In [493]:
losses = []

agents = [1,2]

for game_index in range(number_of_games):
    
    # Switch agent number every game (just to keep the code simpel)
    agent_number = agents[game_index % 2]
    opponent_agent_number = agents[(game_index + 1) % 2]
    
    # Create a new environement
    env = connect.ConnectN()
    
    # Handle the epilon values
    epsilon *= epsilon_decay
    if epsilon < epsilon_min:
        epsilon = epsilon_min
        
    # Play game
    for step_index in range(100):
        # Handle the opponent
        if agent_number != env.current_player and env.is_game_over == False:
        
            # Make observation
            board_data = env.board.reshape(1,6,7,1)
            current_player_data = env.current_player * np.ones((1,6,7,1))
            agent_player_data = env.current_player * np.ones((1,6,7,1))
            opponent_obsv = np.concatenate([board_data, current_player_data, agent_player_data],axis=3)
            
            # Predict Q values of current state
            opponent_q_values = model.predict(opponent_obsv)[0]
            
            # Get action
            legal_actions = env.get_legal_actions()
            action = legal_actions[np.argmax(opponent_q_values[legal_actions])]
            
            # Perform action
            env.step(action)
            continue
              
        # Get current state
        board_data = env.board.reshape(1,6,7,1)
        current_player_data = env.current_player * np.ones((1,6,7,1))
        agent_player_data = agent_number * np.ones((1,6,7,1))
        current_obsv = np.concatenate([board_data, current_player_data, agent_player_data],axis=3)
    
        # Predict Q values of current state
        current_q_values = model.predict(current_obsv)[0]
        # Now we will start with training first
        if step_index > 1:
            
            # Handle rewards
            if env.is_game_over == False:
                reward = 0
            else:
                if env.winner == agent_number:
                    reward = reward_win
                elif env.winner == -1 | env.winner == 0:
                    reward = reward_tie
                else:
                    reward = reward_lose
                    
            # Add experience to memory
            memory.add_event(previous_obsv[0], current_obsv[0], previous_action, reward, not env.is_game_over)
        
        # Now we have to break the loop because we want to train a batch after we have won
        if env.is_game_over:
            break
        
        # Determine action
        if random.random() < epsilon:
            # Perform random action
            action = env.get_legal_random_action()
        else:
            legal_actions = env.get_legal_actions()
            action = legal_actions[np.argmax(current_q_values[legal_actions])]
            
        # Perform action
        env.step(action)
        
        # Store the current state and q values
        previous_obsv = current_obsv
        previous_action = action
        
    # Train
    batch = memory.take_batch()

    batch_size = len(batch[0])
    state = batch[0]
    next_state = batch[1]
    actions = batch[2].astype(int)
    rewards = batch[3]
    is_alives = batch[4]

    # Current state Q values
    q_current_values = model.predict(state)

    # Next state Q values
    q_next_values = model.predict(next_state)
    q_max_next_values = np.max(q_next_values,axis=1)

    # Calculate the new Q values
    new_q_values = rewards + gamma * q_max_next_values * is_alives

    # Set the new Q values
    q_current_values[range(batch_size), actions] = new_q_values
    
    # Train it to ignore saturated columns
    q_current_values[state[:,0,:,0] != 0] = 0

    # Train the model
    loss = model.train_on_batch(state, q_current_values)

    # Append loss
    losses.append(loss)

    # Some monitoring
    if game_index % 10 ==0:
        print(game_index, np.mean(losses[-10:]), epsilon)

0 0.012224093079566956 0.1
10 0.013413038477301598 0.1
20 0.015182031411677599 0.1
30 0.011506189964711666 0.1
40 0.012492447067052126 0.1
50 0.013216102123260498 0.1
60 0.013699784129858016 0.1
70 0.01406483370810747 0.1
80 0.01584897646680474 0.1
90 0.012955943401902915 0.1
100 0.012005071062594653 0.1
110 0.012849207781255246 0.1
120 0.01219342090189457 0.1
130 0.013304377812892199 0.1
140 0.014062521886080504 0.1
150 0.014419501181691885 0.1
160 0.013965965341776609 0.1
170 0.01234835721552372 0.1
180 0.012877324502915144 0.1
190 0.012739734910428523 0.1
200 0.012272361386567354 0.1
210 0.013105037063360215 0.1
220 0.013049338106065988 0.1
230 0.012989952322095632 0.1
240 0.01270107552409172 0.1
250 0.012460848968476056 0.1
260 0.01316922316327691 0.1
270 0.012349844072014093 0.1
280 0.013686169311404229 0.1
290 0.012753209564834833 0.1
300 0.01256234897300601 0.1
310 0.01131369499489665 0.1
320 0.012964116968214512 0.1
330 0.0133448819629848 0.1
340 0.012775131175294519 0.1
350 0.

2800 0.01557511668652296 0.1
2810 0.014276066701859236 0.1
2820 0.014428535476326942 0.1
2830 0.01452377843670547 0.1
2840 0.014589824061840773 0.1
2850 0.013298731204122305 0.1
2860 0.015060724690556526 0.1
2870 0.01140042133629322 0.1
2880 0.013018117286264896 0.1
2890 0.014144977368414403 0.1
2900 0.013151178508996964 0.1
2910 0.013497798796743154 0.1
2920 0.01449909657239914 0.1
2930 0.014183603040874005 0.1
2940 0.013456743210554123 0.1
2950 0.012182212714105845 0.1
2960 0.01217137584462762 0.1
2970 0.013360038865357637 0.1
2980 0.013039481919258833 0.1
2990 0.014366692584007978 0.1
3000 0.014062930643558503 0.1
3010 0.011506999284029007 0.1
3020 0.013642296753823757 0.1
3030 0.013998686708509922 0.1
3040 0.011278043501079082 0.1
3050 0.013911636359989644 0.1
3060 0.013129805214703083 0.1
3070 0.014873325452208519 0.1
3080 0.01368768820539117 0.1
3090 0.012491363193839788 0.1
3100 0.013364492263644934 0.1
3110 0.014524012990295886 0.1
3120 0.01378394030034542 0.1
3130 0.0143308424

5550 0.014124235231429338 0.1
5560 0.01610357789322734 0.1
5570 0.01473050294443965 0.1
5580 0.015399476885795594 0.1
5590 0.014597937557846307 0.1
5600 0.014330023247748614 0.1
5610 0.014154991135001183 0.1
5620 0.0160114292986691 0.1
5630 0.01513827983289957 0.1
5640 0.015918864496052267 0.1
5650 0.013185613788664341 0.1
5660 0.014688330795615911 0.1
5670 0.014048278797417879 0.1
5680 0.01536690816283226 0.1
5690 0.01599715752527118 0.1
5700 0.015910381358116864 0.1
5710 0.014045788627117872 0.1
5720 0.016028280928730966 0.1
5730 0.01660035764798522 0.1
5740 0.01604850944131613 0.1
5750 0.014245506469160318 0.1
5760 0.01435541659593582 0.1
5770 0.014913989137858153 0.1
5780 0.014753235597163438 0.1
5790 0.01553478827700019 0.1
5800 0.015659895073622466 0.1
5810 0.014167503733187915 0.1
5820 0.01653902782127261 0.1
5830 0.015512847248464823 0.1
5840 0.015088073536753654 0.1
5850 0.01764675313606858 0.1
5860 0.015677942615002393 0.1
5870 0.016828727349638938 0.1
5880 0.0156688484363257

8310 0.012868172302842141 0.1
8320 0.013496970850974321 0.1
8330 0.01167995436117053 0.1
8340 0.013487097527831792 0.1
8350 0.01427403073757887 0.1
8360 0.013349034637212754 0.1
8370 0.01413397016003728 0.1
8380 0.013427735213190318 0.1
8390 0.012401655409485101 0.1
8400 0.012422375613823533 0.1
8410 0.01294780634343624 0.1
8420 0.013627263810485601 0.1
8430 0.012212365679442883 0.1
8440 0.011575109511613845 0.1
8450 0.013930882699787617 0.1
8460 0.013527598790824413 0.1
8470 0.01393359238281846 0.1
8480 0.013375358376652002 0.1
8490 0.014020433556288481 0.1
8500 0.013098390772938728 0.1
8510 0.014651825278997421 0.1
8520 0.0148786217905581 0.1
8530 0.01395928831771016 0.1
8540 0.013148438185453415 0.1
8550 0.012421305943280458 0.1
8560 0.013519005477428436 0.1
8570 0.014221603143960237 0.1
8580 0.013384286127984524 0.1
8590 0.014548063464462756 0.1
8600 0.012685360107570886 0.1
8610 0.012628578208386898 0.1
8620 0.013839568570256233 0.1
8630 0.014155033975839615 0.1
8640 0.01397361764

KeyboardInterrupt: 

## Exercise 16)
Play against the new AI

In [404]:
env = connect.ConnectN()

In [405]:
print(env)

# Get observation
board_data = env.board.reshape(1,6,7,1)
current_player_data = env.current_player * np.ones((1,6,7,1))
agent_player_data = agent_number * np.ones((1,6,7,1))
current_obsv = np.concatenate([board_data, current_player_data, agent_player_data],axis=3)

# Predict Q values of current state
current_q_values = model.predict(current_obsv)[0]

# Determine action
legal_actions = env.get_legal_actions()
action = legal_actions[np.argmax(current_q_values[legal_actions])]

# Perform action
env.step(action)

print(env)

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]]


Against itself

In [434]:
env.step(4)

IndexError: index -1 is out of bounds for axis 0 with size 0

## Exercise 17)

Create a code in which the AI playes against itself. Show intermediate states

In [494]:
env = connect.ConnectN()
while not env.is_game_over:
    # Get observation
    board_data = env.board.reshape(1,6,7,1)
    current_player_data = env.current_player * np.ones((1,6,7,1))
    agent_player_data = agent_number * np.ones((1,6,7,1))
    current_obsv = np.concatenate([board_data, current_player_data, agent_player_data],axis=3)

    # Predict Q values of current state
    current_q_values = model.predict(current_obsv)[0]
    
    print(current_q_values)

    # Determine action
    legal_actions = env.get_legal_actions()
    action = legal_actions[np.argmax(current_q_values[legal_actions])]

    # Perform action
    env.step(action)

    print(env)

[0.6271701  0.45908785 0.6429554  0.72995234 0.614094   0.5000298
 0.63782346]
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0]]
[0.6748078  0.5503269  0.63948405 0.73310965 0.6678338  0.60259837
 0.6942271 ]
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 2 0 0 0]
 [0 0 0 1 0 0 0]]
[0.42070708 0.36731791 0.45950663 0.53780323 0.47609875 0.3225355
 0.46273395]
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 2 0 0 0]
 [0 0 0 1 0 0 0]]
[0.48827198 0.55383444 0.49418205 0.38170543 0.5603032  0.4833511
 0.5344986 ]
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 2 0 0 0]
 [0 0 0 1 2 0 0]]
[0.3502672  0.34717494 0.2966642  0.45847777 0.37041643 0.2730353
 0.37704083]
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 2 0 0 0]
 [0 0 0 1 2 0 0]]
[0.4918293  0.51324034 0.40444183 0.45736817 0.5969237  0.51173156
 0.60260355]
[[0 0 0 0

In [495]:
# model.save_weights("../weights/connect_4.h5")